### ISSUE TITLE
Zacykleni

### ISSUE THREAD

**Issue by nomad-cc20** [pichda/ICSHP#3]
https://github.com/pichda/ICSHP/blob/a15e51c249d89dbf00dd2e86f36bf6f6576f7512/Cv08/Genericita/Genericita/MinMaxHashTable.cs#L151

Hondota promenne aktualni se v cyklu nemeni, tedy pokud hledany prvek neni v seznamu na prvnim miste, podminka v tele cyklu se nesplni a cyklus pokracuje do nekonecna.

**Comment by pichda** [comment]
Zapomenuty radek byl pridan. Viz radek 157.
